# Use container-based infrastructure
sudo: false
language: scala
jdk: oraclejdk8
scala:
  - 2.11.11
  - 2.12.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/32ddd4b3099053341d35
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
